# HTTP Server
server:
  port: 8084    # HTTP (Tomcat) port
  
# Application Name
spring:
 application:
  name: rest-service-saludo

# Discovery Server Access
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

